---
title: "Package Creation"
author: "Sanatan Das"
date: "April 16, 2018"
output:
  html_document:
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r var1, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}

predict_default_rate <- function(test_date) {
  load_packages()
  return(predict(fit_default_rate(tidy_data(load_data())), test_date))
}


load_packages <- function() {
  library(tidyverse)
  library(readxl)
  library(broom)
  library(knitr)
}

load_data <- function() {
  default_rates <- read_excel("C:/view/opt/apps/git/compscix-415-1-assignments/data/peps3xx.xls")
  return(default_rates)
}

tidy_data <- function(default_rates) {
  # add factor to the 'char' columns
  default_rates$Name <- as.factor(default_rates$Name)
  default_rates$State <- as.factor(default_rates$State)
  default_rates$ZipCode <- as.factor(default_rates$ZipCode)
  default_rates$ProgLength <- as.factor(default_rates$ProgLength)
  default_rates$SchoolType <- as.factor(default_rates$SchoolType)
  default_rates$EthnicCode <- as.factor(default_rates$EthnicCode)
  default_rates$Prate <- as.factor(default_rates$Prate)
  default_rates$CongDis <- as.factor(default_rates$CongDis)
  # convert the columns to 'double' data type
  default_rates$Drate <- as.double(default_rates$Drate)
  default_rates$Num <- as.double(default_rates$Num)
  default_rates$Denom <- as.double(default_rates$Denom)
  return(default_rates)
}

fit_default_rate <- function(default_rates) {
  lm_0 <- lm(Drate ~ ProgLength + SchoolType + Num + Denom + Prate + EthnicCode, data = default_rates)
  return(lm_0)
}



```


```{r var2, eval=TRUE, echo=TRUE}
library(tidyverse)
library(readxl)
library(broom)
library(knitr)
default_rates <- tidy_data(read_excel("C:/view/opt/apps/git/compscix-415-1-assignments/data/peps3xx.xls"))
default_rates[1,]$Drate
prediction <- predict_default_rate(default_rates[1,])
prediction

```


